# Generated by Django 4.2.2 on 2025-05-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="نص السؤال")),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("software", "هندسة البرمجيات"),
                            ("networks", "هندسة الشبكات"),
                            ("ai", "الذكاء الاصطناعي"),
                            ("general", "التخصص العام"),
                        ],
                        max_length=20,
                        verbose_name="التخصص",
                    ),
                ),
                ("year", models.CharField(max_length=4, verbose_name="سنة الدورة")),
                (
                    "marks",
                    models.PositiveSmallIntegerField(default=1, verbose_name="العلامة"),
                ),
                (
                    "has_attachment",
                    models.BooleanField(default=False, verbose_name="يحتوي على مرفق"),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("image", "صورة"),
                            ("code", "كود"),
                            ("text", "نص"),
                            ("diagram", "رسم تخطيطي"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="نوع المرفق",
                    ),
                ),
                (
                    "attachment_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="محتوى المرفق"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "سؤال",
                "verbose_name_plural": "أسئلة",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="نص الخيار")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="إجابة صحيحة"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "خيار",
                "verbose_name_plural": "خيارات",
            },
        ),
    ]
