# Generated by Django 4.2.2 on 2025-05-09 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("software", "هندسة البرمجيات"),
                            ("networks", "هندسة الشبكات"),
                            ("ai", "الذكاء الاصطناعي"),
                            ("general", "التخصص العام"),
                        ],
                        max_length=20,
                        verbose_name="التخصص",
                    ),
                ),
                (
                    "question_count",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="عدد الأسئلة"
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="الوقت (بالدقائق)"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت البدء"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت الانتهاء"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "جارٍ"),
                            ("completed", "مكتمل"),
                            ("expired", "منتهي"),
                        ],
                        default="ongoing",
                        max_length=10,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="العلامة"
                    ),
                ),
                (
                    "correct_answers",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="الإجابات الصحيحة"
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="النسبة المئوية"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "امتحان",
                "verbose_name_plural": "امتحانات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="الترتيب"),
                ),
                (
                    "user_answer",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="إجابة المستخدم"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="إجابة صحيحة"
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "سؤال امتحان",
                "verbose_name_plural": "أسئلة امتحان",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(
                through="exams.ExamQuestion",
                to="questions.question",
                verbose_name="الأسئلة",
            ),
        ),
    ]
