# Generated by Django 5.2 on 2025-05-19 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_initial"),
    ]

    operations = [
    ]
