# Generated by Django 4.2.2 on 2025-05-25 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_aimodel_exam_exam_type_exam_ai_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم النموذج')),
                ('api_key', models.CharField(max_length=255, verbose_name='مفتاح API')),
                ('model_identifier', models.CharField(help_text='المعرف المستخدم لاستدعاء API النموذج', max_length=100, verbose_name='معرف النموذج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'نموذج ذكاء اصطناعي',
                'verbose_name_plural': 'نماذج الذكاء الاصطناعي',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('normal', 'امتحان عادي'), ('ai', 'امتحان ذكي')], default='normal', max_length=10, verbose_name='نوع الامتحان'),
        ),
        migrations.AddField(
            model_name='exam',
            name='ai_model',
            field=models.ForeignKey(blank=True, help_text='يستخدم فقط إذا كان نوع الامتحان ذكي', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.aimodel', verbose_name='نموذج الذكاء الاصطناعي'),
        ),
    ]
